name: local_storage_todo_api
description: storage with hive db for saving and getting all todos.
publish_to: "none"
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  hive: ^2.2.2
  base_repository:
    path: ../base_repository/
  todo_api:
    path: ../todo_api/