name: todo_api
description: todo_api that have model of todo
publish_to: "none"

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  equatable: ^2.0.3
  base_repository:
    path: ../base_repository/
