name: todo_repository
description: todo_repository for this application
publish_to: "none"
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  todo_api:
    path: ../todo_api/
  base_repository:
    path: ../base_repository/
  local_storage_todo_api:
    path: ../local_storage_todo_api/
